const categories = [
  {
    name: 'Women',
    slug: 'women',
    description: 'Designer lehengas and sarees crafted for festive elegance.',
    subCategories: ['Lehenga', 'Saree'],
    image: 'https://source.unsplash.com/1200x800/?indian,women,lehenga,fashion',
  },
  {
    name: 'Men',
    slug: 'men',
    description: 'Regal sherwanis and kurtas inspired by classic Indian silhouettes.',
    subCategories: ['Sherwani', 'Kurta'],
    image: 'https://source.unsplash.com/1200x800/?indian,men,sherwani,kurta,fashion',
  },
  {
    name: 'Kids',
    slug: 'kids',
    description: 'Comfortable occasion wear for boys and girls.',
    subCategories: ['Boys', 'Girls'],
    image: 'https://source.unsplash.com/1200x800/?kids,indian,traditional,fashion',
  },
];

const productSeeds = [
  {
    name: 'Rang Mahal Bridal Lehenga',
    price: 45999,
    description: 'Heavy hand-embroidered bridal lehenga with zardozi and mirror detailing.',
    shortDescription: 'Bridal lehenga with zardozi work',
    categoryName: 'Women',
    subCategory: 'Lehenga',
    gender: 'women',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Maroon', hex: '#6d102f' },
      { name: 'Gold', hex: '#c89b3c' },
    ],
    stock: 8,
    popularity: 97,
    featured: true,
    trending: true,
    material: 'Raw silk and net',
  },
  {
    name: 'Noor Banarasi Lehenga',
    price: 32999,
    description: 'Banarasi weave lehenga set with contrast dupatta and sequined blouse.',
    shortDescription: 'Banarasi festive lehenga set',
    categoryName: 'Women',
    subCategory: 'Lehenga',
    gender: 'women',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [
      { name: 'Royal Blue', hex: '#1f3a8a' },
      { name: 'Rose Pink', hex: '#f472b6' },
    ],
    stock: 12,
    popularity: 82,
    featured: true,
    trending: false,
    material: 'Banarasi silk',
  },
  {
    name: 'Gulnaar Festive Lehenga',
    price: 28999,
    description: 'Panel-cut lehenga with gota patti accents and lightweight cancan.',
    shortDescription: 'Panel lehenga with gota patti',
    categoryName: 'Women',
    subCategory: 'Lehenga',
    gender: 'women',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Coral', hex: '#fb7185' },
      { name: 'Ivory', hex: '#f8f4e8' },
    ],
    stock: 14,
    popularity: 74,
    featured: false,
    trending: true,
    material: 'Georgette and organza',
  },
  {
    name: 'Mehr Crimson Lehenga',
    price: 39999,
    description: 'Couture lehenga with hand-cut sequins and multi-layer flare.',
    shortDescription: 'Couture crimson lehenga',
    categoryName: 'Women',
    subCategory: 'Lehenga',
    gender: 'women',
    sizes: ['S', 'M', 'L'],
    colors: [
      { name: 'Crimson', hex: '#7f1d1d' },
      { name: 'Champagne', hex: '#f5e7c3' },
    ],
    stock: 5,
    popularity: 88,
    featured: false,
    trending: true,
    material: 'Velvet and tissue',
  },
  {
    name: 'Kashvi Kanjivaram Saree',
    price: 18999,
    description: 'Pure silk Kanjivaram saree with temple border and zari motifs.',
    shortDescription: 'Traditional Kanjivaram silk saree',
    categoryName: 'Women',
    subCategory: 'Saree',
    gender: 'women',
    sizes: ['M', 'L', 'XL'],
    colors: [
      { name: 'Emerald', hex: '#065f46' },
      { name: 'Antique Gold', hex: '#b0893f' },
    ],
    stock: 20,
    popularity: 91,
    featured: true,
    trending: true,
    material: 'Pure silk',
  },
  {
    name: 'Ziya Organza Saree',
    price: 14999,
    description: 'Soft organza saree with threadwork floral vines and scalloped pallu.',
    shortDescription: 'Organza threadwork saree',
    categoryName: 'Women',
    subCategory: 'Saree',
    gender: 'women',
    sizes: ['S', 'M', 'L'],
    colors: [
      { name: 'Powder Blue', hex: '#bfdbfe' },
      { name: 'Silver', hex: '#9ca3af' },
    ],
    stock: 25,
    popularity: 69,
    featured: false,
    trending: false,
    material: 'Organza',
  },
  {
    name: 'Aabha Tissue Saree',
    price: 16999,
    description: 'Luminous tissue saree with pearl border and handworked blouse piece.',
    shortDescription: 'Pearl border tissue saree',
    categoryName: 'Women',
    subCategory: 'Saree',
    gender: 'women',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Champagne', hex: '#f1e2c6' },
      { name: 'Copper', hex: '#b45309' },
    ],
    stock: 18,
    popularity: 77,
    featured: false,
    trending: true,
    material: 'Tissue silk',
  },
  {
    name: 'Rivaa Chikankari Saree',
    price: 13999,
    description: 'Lucknowi chikankari saree with hand-finished mukaish highlights.',
    shortDescription: 'Chikankari saree with mukaish',
    categoryName: 'Women',
    subCategory: 'Saree',
    gender: 'women',
    sizes: ['S', 'M', 'L'],
    colors: [
      { name: 'Blush', hex: '#fbcfe8' },
      { name: 'Ivory', hex: '#f8f4e8' },
    ],
    stock: 16,
    popularity: 72,
    featured: true,
    trending: false,
    material: 'Cotton silk',
  },
  {
    name: 'Rajvansh Velvet Sherwani',
    price: 27999,
    description: 'Velvet sherwani with tonal embroidery and handcrafted buttons.',
    shortDescription: 'Velvet embroidered sherwani',
    categoryName: 'Men',
    subCategory: 'Sherwani',
    gender: 'men',
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Navy', hex: '#1e3a8a' },
      { name: 'Wine', hex: '#7f1d1d' },
    ],
    stock: 10,
    popularity: 94,
    featured: true,
    trending: true,
    material: 'Velvet',
  },
  {
    name: 'Aariz Ivory Sherwani',
    price: 25999,
    description: 'Classic ivory sherwani with subtle tonal threadwork for weddings.',
    shortDescription: 'Ivory sherwani for groom',
    categoryName: 'Men',
    subCategory: 'Sherwani',
    gender: 'men',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Ivory', hex: '#fef3c7' },
      { name: 'Sand', hex: '#d6c7a1' },
    ],
    stock: 11,
    popularity: 86,
    featured: false,
    trending: true,
    material: 'Silk jacquard',
  },
  {
    name: 'Farhan Indo-Western Sherwani',
    price: 23999,
    description: 'Asymmetric sherwani with metallic thread detailing and draped stole.',
    shortDescription: 'Indo-western asymmetric sherwani',
    categoryName: 'Men',
    subCategory: 'Sherwani',
    gender: 'men',
    sizes: ['M', 'L', 'XL'],
    colors: [
      { name: 'Charcoal', hex: '#1f2937' },
      { name: 'Stone', hex: '#9ca3af' },
    ],
    stock: 13,
    popularity: 79,
    featured: true,
    trending: false,
    material: 'Brocade and crepe',
  },
  {
    name: 'Samar Silk Sherwani',
    price: 29999,
    description: 'Silk sherwani with antique dabka motifs and matching churidar.',
    shortDescription: 'Silk sherwani with antique motifs',
    categoryName: 'Men',
    subCategory: 'Sherwani',
    gender: 'men',
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Bottle Green', hex: '#14532d' },
      { name: 'Gold', hex: '#c89b3c' },
    ],
    stock: 7,
    popularity: 84,
    featured: false,
    trending: true,
    material: 'Silk blend',
  },
  {
    name: 'Reyaan Linen Kurta Set',
    price: 6999,
    description: 'Breathable linen kurta set with contrast piping and tapered pants.',
    shortDescription: 'Linen kurta with tapered pants',
    categoryName: 'Men',
    subCategory: 'Kurta',
    gender: 'men',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Olive', hex: '#4d7c0f' },
      { name: 'Beige', hex: '#e5d3b3' },
    ],
    stock: 30,
    popularity: 71,
    featured: false,
    trending: false,
    material: 'Linen',
  },
  {
    name: 'Vyaan Festive Kurta',
    price: 8999,
    description: 'Textured festive kurta with mirror buttons and churidar.',
    shortDescription: 'Festive mirror-button kurta',
    categoryName: 'Men',
    subCategory: 'Kurta',
    gender: 'men',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Mustard', hex: '#ca8a04' },
      { name: 'Off White', hex: '#f8fafc' },
    ],
    stock: 24,
    popularity: 76,
    featured: true,
    trending: true,
    material: 'Cotton silk',
  },
  {
    name: 'Arham Classic Kurta',
    price: 5999,
    description: 'Minimal kurta in premium cotton for puja and family events.',
    shortDescription: 'Classic cotton kurta',
    categoryName: 'Men',
    subCategory: 'Kurta',
    gender: 'men',
    sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL'],
    colors: [
      { name: 'White', hex: '#ffffff' },
      { name: 'Sky Blue', hex: '#7dd3fc' },
    ],
    stock: 40,
    popularity: 68,
    featured: false,
    trending: false,
    material: 'Premium cotton',
  },
  {
    name: 'Kabir Pathani Kurta',
    price: 7499,
    description: 'Pathani-inspired kurta with structured shoulders and comfort fit.',
    shortDescription: 'Pathani style kurta set',
    categoryName: 'Men',
    subCategory: 'Kurta',
    gender: 'men',
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Black', hex: '#111827' },
      { name: 'Rust', hex: '#b45309' },
    ],
    stock: 19,
    popularity: 73,
    featured: false,
    trending: true,
    material: 'Rayon blend',
  },
  {
    name: 'Aarohi Girls Lehenga Set',
    price: 5499,
    description: 'Twirl-friendly girls lehenga set with light embroidery and tassels.',
    shortDescription: 'Girls festive lehenga set',
    categoryName: 'Kids',
    subCategory: 'Girls',
    gender: 'girls',
    sizes: ['4-5Y', '6-7Y', '8-9Y', '10-11Y'],
    colors: [
      { name: 'Peach', hex: '#fdba74' },
      { name: 'Pink', hex: '#f472b6' },
    ],
    stock: 35,
    popularity: 85,
    featured: true,
    trending: true,
    material: 'Net and satin',
  },
  {
    name: 'Misha Girls Saree Gown',
    price: 4999,
    description: 'Pre-stitched saree gown for girls with lightweight drape and belt.',
    shortDescription: 'Pre-stitched saree gown',
    categoryName: 'Kids',
    subCategory: 'Girls',
    gender: 'girls',
    sizes: ['6-7Y', '8-9Y', '10-11Y', '12-13Y'],
    colors: [
      { name: 'Lilac', hex: '#c4b5fd' },
      { name: 'Silver', hex: '#d1d5db' },
    ],
    stock: 28,
    popularity: 66,
    featured: false,
    trending: false,
    material: 'Georgette',
  },
  {
    name: 'Trisha Girls Anarkali',
    price: 4699,
    description: 'Anarkali set with gotta lace and soft dupatta for celebrations.',
    shortDescription: 'Girls anarkali set',
    categoryName: 'Kids',
    subCategory: 'Girls',
    gender: 'girls',
    sizes: ['4-5Y', '6-7Y', '8-9Y', '10-11Y', '12-13Y'],
    colors: [
      { name: 'Mint', hex: '#6ee7b7' },
      { name: 'Ivory', hex: '#f8f4e8' },
    ],
    stock: 31,
    popularity: 70,
    featured: false,
    trending: true,
    material: 'Chanderi',
  },
  {
    name: 'Yuvan Boys Sherwani Set',
    price: 5999,
    description: 'Boys sherwani with nehru collar and matching pants for weddings.',
    shortDescription: 'Boys sherwani set',
    categoryName: 'Kids',
    subCategory: 'Boys',
    gender: 'boys',
    sizes: ['4-5Y', '6-7Y', '8-9Y', '10-11Y', '12-13Y'],
    colors: [
      { name: 'Navy', hex: '#1e3a8a' },
      { name: 'Cream', hex: '#fef9c3' },
    ],
    stock: 26,
    popularity: 88,
    featured: true,
    trending: true,
    material: 'Jacquard silk',
  },
  {
    name: 'Arjun Boys Kurta Jacket Set',
    price: 4299,
    description: 'Kurta pajama with printed jacket designed for all-day comfort.',
    shortDescription: 'Boys kurta with jacket',
    categoryName: 'Kids',
    subCategory: 'Boys',
    gender: 'boys',
    sizes: ['4-5Y', '6-7Y', '8-9Y', '10-11Y'],
    colors: [
      { name: 'Teal', hex: '#0f766e' },
      { name: 'Beige', hex: '#e5d3b3' },
    ],
    stock: 42,
    popularity: 64,
    featured: false,
    trending: false,
    material: 'Cotton blend',
  },
  {
    name: 'Ved Boys Festive Kurta',
    price: 3599,
    description: 'Soft cotton festive kurta with dhoti bottoms for ceremonies.',
    shortDescription: 'Boys festive kurta and dhoti',
    categoryName: 'Kids',
    subCategory: 'Boys',
    gender: 'boys',
    sizes: ['4-5Y', '6-7Y', '8-9Y'],
    colors: [
      { name: 'Marigold', hex: '#f59e0b' },
      { name: 'White', hex: '#ffffff' },
    ],
    stock: 37,
    popularity: 62,
    featured: false,
    trending: true,
    material: 'Cotton',
  },
  {
    name: 'Kia Kids Sibling Festive Combo',
    price: 7999,
    description: 'Coordinated festive combo for siblings with coordinated prints.',
    shortDescription: 'Matching sibling festive set',
    categoryName: 'Kids',
    subCategory: 'Girls',
    gender: 'unisex',
    sizes: ['6-7Y', '8-9Y', '10-11Y'],
    colors: [
      { name: 'Lavender', hex: '#a78bfa' },
      { name: 'Gold', hex: '#eab308' },
    ],
    stock: 15,
    popularity: 59,
    featured: true,
    trending: false,
    material: 'Silk blend',
  },
];

module.exports = {
  categories,
  productSeeds,
};
